# Generated by Django 5.2.17 on 2026-09-03 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_historicalconsent'),
        ('people', '0002_historicalstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('arrived_at', models.TimeField(blank=True, help_text='Only for a late arrival.', null=True)),
                ('left_at', models.TimeField(blank=True, help_text='Only for an early pickup.', null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='core.classroom')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.student')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PickupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_name', models.CharField(blank=True, max_length=200)),
                ('override_reason', models.CharField(blank=True, max_length=300)),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='attendance.attendancerecord')),
                ('authorized_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='people.authorizedpickup')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='people.guardian')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickups_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.staff')),
            ],
            options={
                'verbose_name_plural': 'staff attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['classroom', 'date'], name='attendance_room_day_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance_child_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='one_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='pickuprecord',
            constraint=models.CheckConstraint(condition=models.Q(('authorized_pickup__isnull', False), ('guardian__isnull', False), models.Q(models.Q(('override_name', ''), _negated=True), models.Q(('override_reason', ''), _negated=True)), _connector='OR'), name='pickup_identifies_someone'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='one_staff_attendance_per_day'),
        ),
    ]
