# Generated by Django 5.2.17 on 2026-09-02 15:34

import django.core.validators
import django.db.models.deletion
import integrations.storage_r2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalconsent'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Landscape, roughly 4:3. A programme without one renders as a text card rather than an empty box.', storage=integrations.storage_r2.public_media, upload_to='marketing/programs/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='The photograph behind the home page headline. Landscape, at least 1400px wide. Without one the hero falls back to colour and type.', storage=integrations.storage_r2.public_media, upload_to='marketing/site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='What the photograph shows, for a screen reader. Leave blank if it is purely decorative.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional. Without one the header shows the Aaroham wordmark, which is no bad thing.', storage=integrations.storage_r2.public_media, upload_to='marketing/site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Country code + number, digits only. Shows a WhatsApp button on every public page. Leave blank to hide it.', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Digits only, including the country code — e.g. 919876543210.')]),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=integrations.storage_r2.public_media, upload_to='marketing/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='What the photograph shows. Leave blank only if it is purely decorative — an empty alt is correct markup for that, a missing one is not.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('placement', models.CharField(choices=[('gallery', 'Gallery — the strip on the home page'), ('about', 'About us'), ('approach_play', 'Our approach — learning through play'), ('approach_hands', 'Our approach — hands-on and independent'), ('approach_values', 'Our approach — Indian values and culture'), ('inclusion', 'Thoughtful education'), ('team', 'Our team — the band above the educators')], default='gallery', max_length=20)),
                ('source_key', models.CharField(blank=True, editable=False, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('branch', 'source_key'), name='uniq_gallery_source_per_branch')],
            },
        ),
    ]
