# Generated by Django 5.2.17 on 2026-09-02 16:02

import integrations.storage_r2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_marketing_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(max_length=200, storage=integrations.storage_r2.public_media, upload_to='marketing/gallery/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Landscape, roughly 4:3. A programme without one renders as a text card rather than an empty box.', max_length=200, storage=integrations.storage_r2.public_media, upload_to='marketing/programs/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='The photograph behind the home page headline. Landscape, at least 1400px wide. Without one the hero falls back to colour and type.', max_length=200, storage=integrations.storage_r2.public_media, upload_to='marketing/site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional. Without one the header shows the Aaroham wordmark, which is no bad thing.', max_length=200, storage=integrations.storage_r2.public_media, upload_to='marketing/site/'),
        ),
    ]
