# Generated by Django 5.2.17 on 2026-09-09 03:23

import integrations.storage_r2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_widen_image_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, storage=integrations.storage_r2.public_media, upload_to='team/'),
        ),
    ]
