# Generated by Django 5.2.17 on 2026-09-04 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_historicalconsent'),
        ('people', '0002_historicalstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_state', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='activities.mediaasset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tags', to='people.student')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_tags_applied', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='students',
            field=models.ManyToManyField(related_name='media_assets', through='activities.MediaTag', to='people.student'),
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('meal', 'Meal'), ('nap', 'Nap'), ('learning', 'Learning'), ('note', 'Note'), ('milestone', 'Milestone')], max_length=20)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_entries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_entries', to='core.classroom')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_entries', to='people.student')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['-occurred_at'], name='activity_occurred_idx'), models.Index(fields=['student', '-occurred_at'], name='activity_student_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('classroom__isnull', True), ('student__isnull', False)), models.Q(('classroom__isnull', False), ('student__isnull', True)), _connector='OR'), name='activity_targets_student_xor_classroom')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('what_happened', models.TextField()),
                ('action_taken', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('staff_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_responsible', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='people.student')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['student', '-occurred_at'], name='incident_student_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediatag',
            constraint=models.UniqueConstraint(fields=('media', 'student'), name='uniq_media_student_tag'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['-taken_at'], name='media_taken_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['upload_state'], name='media_upload_state_idx'),
        ),
    ]
